version: '3'

services:

  db:
    image: postgres:15-alpine
    container_name: wikijs-database
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - wikijs-iso
    logging:
      driver: "none"
    volumes:
      - ./data:/var/lib/postgresql/data

  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs-service
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
      - wikijs-iso
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: $POSTGRES_USER
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: $POSTGRES_DB
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wiki.entrypoints=http"
      - "traefik.http.routers.wiki.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.wiki-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.wiki.middlewares=wiki-https-redirect"
      - "traefik.http.routers.wiki-secure.entrypoints=https"
      - "traefik.http.routers.wiki-secure.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.wiki-secure.tls=true"
      - "traefik.http.routers.wiki-secure.service=wiki"
      - "traefik.http.services.wiki.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  db-data:

networks:
  proxy:
    external: true
  wikijs-iso:
    external: true