version: '3'

services:
  mariadb:
    image: mariadb:latest
    container_name: dolibarr-database
    restart: on-failure:5
    security_opt:
      - no-new-privileges:true
    networks:
      - dolibarr-iso
    volumes:
      - /mnt/dolibarr/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE

  web:
    image: tuxgasy/dolibarr
    container_name: dolibarr-service
    networks:
      - proxy
      - dolibarr-iso
    environment:
      DOLI_DB_HOST: mariadb
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      DOLI_DB_NAME: $MYSQL_DATABASE
      DOLI_URL_ROOT: 'http://0.0.0.0'
      PHP_INI_DATE_TIMEZONE: $PHP_INI_DATE_TIMEZONE
      DOLI_INSTALL_AUTO: 1
      DOLI_PROD: 1
      DOLI_ADMIN_LOGIN: $DOLI_ADMIN_LOGIN
      DOLI_ADMIN_PASSWORD: $DOLI_ADMIN_PASSWORD
    volumes:
      - /mnt/dolibarr/html:/var/www/html/custom:rw
      - /mnt/dolibarr/docs:/var/www/documents:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dolibarr.entrypoints=http"
      - "traefik.http.routers.dolibarr.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.middlewares.dolibarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dolibarr.middlewares=dolibarr-https-redirect"
      - "traefik.http.routers.dolibarr-secure.entrypoints=https"
      - "traefik.http.routers.dolibarr-secure.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.dolibarr-secure.tls=true"
      - "traefik.http.routers.dolibarr-secure.service=dolibarr"
      - "traefik.http.services.dolibarr.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      # Enable Watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    links:
      - mariadb

networks:
  proxy:
    external: true
  dolibarr-iso:
    external: true
